### ISSUE TITLE
Developer advice for cydia slowdowns and crashes.

### ISSUE THREAD

**Issue by xevidos** [jlippold/tweakCompatible#1945]
Hello,

I wanted to let you know it may be a good idea to display a loading message while your tweak is gathering information from the server.  You could do this by creating a separate thread and loading you info in there.  This might help with the cydia freezes and slowdowns.

https://stackoverflow.com/questions/25939073/running-a-task-in-background-thread-periodically-in-ios

Here is a thread on running a task in the background if you are using objective c.

**Comment by jlippold** [comment]
Earlier builds had background threads, but i removed them when debugging crashes. The blocking the thread was not the reason for the slowdowns. The slowdowns occurred because of some differences in the electra jailbreak as described here https://github.com/ElectraJailbreak/cydia/issues/4

The slowdowns are fixed in 0.0.5 by avoiding webview injection entirlely
