### ISSUE TITLE
`TranslucentMessages` working on iOS 11.1.2

### ISSUE THREAD

**Issue by xrouk** [jlippold/tweakCompatible#3103]
```
{
  "packageId": "com.yourepo.kiiimo.translucentmessages",
  "action": "working",
  "userInfo": {
    "arch32": false,
    "packageId": "com.yourepo.kiiimo.translucentmessages",
    "deviceId": "iPhone9,4",
    "url": "http://cydia.saurik.com/package/com.yourepo.kiiimo.translucentmessages/",
    "iOSVersion": "11.1.2",
    "packageVersionIndexed": false,
    "packageName": "TranslucentMessages",
    "category": "Supports iOS 11",
    "repository": "A KiiiMO GC - ARABIC ï£¿",
    "name": "TranslucentMessages",
    "packageIndexed": false,
    "packageStatusExplaination": "This tweak has not been reviewed. Please submit a review if you choose to install.",
    "id": "com.yourepo.kiiimo.translucentmessages",
    "commercial": false,
    "packageInstalled": true,
    "tweakCompatVersion": "0.0.6",
    "shortDescription": "Ø§ÙØ±Ø³Ø§Ø¦Ù Ø´ÙØ§ÙØ© ÙÙ ØªØ·Ø¨ÙÙ Ø§ÙØ±Ø³Ø§Ø¦Ù âªnow available as a beta for all patrons! We've been working hard to make sure everything is perfect, and that the tweak looks better than ever before. We can't wait to see your setups!â¬",
    "latest": "1.1",
    "author": "AppleBeta",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20ueW91cmVwby5raWlpbW8udHJhbnNsdWNlbnRtZXNzYWdlcyIsImRldmljZUlkIjoiaVBob25lOSw0IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnlvdXJlcG8ua2lpaW1vLnRyYW5zbHVjZW50bWVzc2FnZXNcLyIsImlPU1ZlcnNpb24iOiIxMS4xLjIiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJwYWNrYWdlTmFtZSI6IlRyYW5zbHVjZW50TWVzc2FnZXMiLCJjYXRlZ29yeSI6IlN1cHBvcnRzIGlPUyAxMSIsInJlcG9zaXRvcnkiOiJBIEtpaWlNTyBHQyAtIEFSQUJJQyDvo78iLCJuYW1lIjoiVHJhbnNsdWNlbnRNZXNzYWdlcyIsInBhY2thZ2VJbmRleGVkIjpmYWxzZSwicGFja2FnZVN0YXR1c0V4cGxhaW5hdGlvbiI6IlRoaXMgdHdlYWsgaGFzIG5vdCBiZWVuIHJldmlld2VkLiBQbGVhc2Ugc3VibWl0IGEgcmV2aWV3IGlmIHlvdSBjaG9vc2UgdG8gaW5zdGFsbC4iLCJpZCI6ImNvbS55b3VyZXBvLmtpaWltby50cmFuc2x1Y2VudG1lc3NhZ2VzIiwiY29tbWVyY2lhbCI6ZmFsc2UsInBhY2thZ2VJbnN0YWxsZWQiOnRydWUsInR3ZWFrQ29tcGF0VmVyc2lvbiI6IjAuMC42Iiwic2hvcnREZXNjcmlwdGlvbiI6Itin2YTYsdiz2KfYptmEINi02YHYp9mB2Kkg2YHZiiDYqti32KjZitmCINin2YTYsdiz2KfYptmEIOKAqm5vdyBhdmFpbGFibGUgYXMgYSBiZXRhIGZvciBhbGwgcGF0cm9ucyEgV2UndmUgYmVlbiB3b3JraW5nIGhhcmQgdG8gbWFrZSBzdXJlIGV2ZXJ5dGhpbmcgaXMgcGVyZmVjdCwgYW5kIHRoYXQgdGhlIHR3ZWFrIGxvb2tzIGJldHRlciB0aGFuIGV2ZXIgYmVmb3JlLiBXZSBjYW4ndCB3YWl0IHRvIHNlZSB5b3VyIHNldHVwcyHigKwiLCJsYXRlc3QiOiIxLjEiLCJhdXRob3IiOiJBcHBsZUJldGEiLCJwYWNrYWdlU3RhdHVzIjoiVW5rbm93biJ9",
  "chosenStatus": "working",
  "notes": "works like a charm!! looks amazing!"
}
```

**Comment by AppleBetas** [comment]
@jlippold Please remove this or we will be forced to DMCA your repository.

**Comment by jlippold** [comment]
I added that repo to the ban list, but dude, you're gonna DMCA a json file in a repo? There's no need to hit me with threats man, just ask me. I dont want pirate tweaks either.

**Comment by EricRabil** [comment]
@jlippold the JSON file refers to pirated assets and we are zero tolerance. Please remove the contents of the comment or we have no choice but to DMCA.

**Comment by AppleBetas** [comment]
Yes. I warned you, something I was under no obligation to do, rather than just DMCAing the repo.

It isn't just a JSON file in a repo, it's part of a popular website that allows users to look up tweaks. It was linking to (and therefore aiding in distributing) a pirated version of my software, probably allowing many users to download this version illegally. Not knowing the kind of site you're running, I brought up DMCA (as it has been difficult to get things removed in the past).

Honestly, we'd rather not DMCA anything. It's more work for us, and it sucks when you have to do that to get someone to comply. I also actually do like this idea for a site and how you've implemented it, but I can't allow it to facilitate illegal downloads of our software. Hopefully you can keep an eye on that and ban any piracy that comes up.

**Comment by jlippold** [comment]
I can’t control what people submit. If you tell me, I’ll remove it, but you don’t have to threaten me. I’m not making a money off this website, I did it because I was trying to give back to the JB community. It’s hosted on GitHub ffs. If you DCMA it, you’re reallly hurting the community, it’s not really hurting me or pirates. I did this for fun, I don’t care. 

All I’m saying is you get more with honey than vinegar, and I’m not pirating anything, so just open an issue asking me, or better yet, create a pull request to help the project and your users.
