### ISSUE TITLE
Piracy flag is getting out of hand

### ISSUE THREAD

**Issue by sietec** [jlippold/tweakCompatible#49956]
To keep this concise, I will give a brief overview of my issue, then paste a more detailed response which I added to a 'working' report that was flagged as piracy simply because of __the repo__ it was installed from.

As a long time developer, I understand and genuinely appreciate and respect the concern over pirated software being 'emphasized' via TCC.  That being said, I feel the inclusion criteria used to mark something as piracy, is way to liberal and blanket covers many non-pirated tweaks.  IMHO, the entire automated process of deciding whether a report is considered piracy needs a major overhaul, if not complete rewrite.

Perhaps, just as users submit ratings of tweaks (which are, generally, relied upon as valid), users (maybe _approved_ users) could be more valuable than several simple algorithms with regards to reporting piracy.  Without some sort of human interaction in the process, it is going to require orders of magnitude more complex algorithms to __-accurately-__ determine whether something is or is not pirated software.  e.g. machine learning would be about the only somewhat capable method to perform such a complex task automatically.  I fear that if @jlippold continues with this strict pattern matching piracy concept, the usefulness of this really awesome idea will be virtually impossible to maintain with more and more users deciding it’s not worth their time or frustration, to the point not enough people will be utilizing it for it to be worthwhile.

I will be happy to help, should @jlippold be interested in working out a new solution to this issue, but I must say that, if he is not, others (possibly myself) will create a similar, but more functional utility.

Most of the ideas I see discussed on this repo are never implemented (other than the piracy thing, of course).  People are here to help you, my friend, take them up on it!

Thanks for listening, I lost my copy/paste so I’ll paste the comment later.

**Comment by jlippold** [comment]
The tweak is open source, if you want to fork it and make it better go ahead man, that's why it's on github. I'd also accept pull requests if you'd like ideas implemented that I don't have the time to do. 

As far as piracy goes, frankly I don't give a shit if pirate tweaks are in the database, but the mods over at /r/jailbreak do. They care so much that any posts referencing tweakCompatible were being deleted. To compromise, I gave all reddit mods the ability to mark pirate repo's and pirate packages. Regular users cannot mark a tweak as piracy. I believe one particular mod, @PJ09github is a little too trigger happy, see all the submissions: https://github.com/jlippold/tweakCompatible/issues?utf8=%E2%9C%93&q=Pirate+Repo

I suggest you start a thread over on r/jailbreak and talk to those mods, because they are the ones determining what's piracy and what's not.

**Comment by PJ09github** [comment]
All those repos are piracy repos/ re hosting without permission

Inviato da iPad

**Comment by PJ09github** [comment]
@jlippold as you can see from your link https://github.com/jlippold/tweakCompatible/issues?utf8=%E2%9C%93&q=Pirate+Repo all those removal are for repos that are hosting piracy/pirated tweaks or are rehosting tweaks without permission.

I have rightly removed `Arab-Cydia™  I سيديـا الـ ع ـرب`, `Xarold Repository`, Jukioverne Xarold repo, `kdog0598's Repository`, `JailbreakTR Repository`, `sharklatan.com`, `Mrmad's Repo`,  `A kiiimo Respositoty `,  `ReJail Repository`, `Hollr2099.net Repo`, `xRepo ™`,  `SiNfuL iPhone Repo`,  `dtathemes Repo` because are all repos that contain piracy/pirated/ rehosted without permission tweaks. (all rightly removed not because "too trigger happy").

**Comment by jlippold** [comment]
Ok @PJ09github i don't know to be honest. I just hear the complaints of things getting removed. I don't care either way because I don't have pirate tweaks on my device, so none of this effects me.

@sietec can you be more specific about what was wrongfully deleted, or do you just have an all around pro piracy stance? I'm not sure what you want me to do here.

**Comment by sietec** [comment]
I really  appreciate the rapid reply., I have to agree with you hundred percent about what’s in the database, I am not in your shoes, however, so I don’t know what they are saying to you and how much leverage they have.

 I know you’re kind of stuck between a rock and a hard place here, and your mission was to create a awesome and user-friendly method of keeping track of which repositories and tweaks work with each new version of iOS.

You have done an absolutely fantastic job, I will be more than happy to try to work with you and help figure out a solution that makes everybody happy (as happy as possible).

 I guess the main reason I wrote such a long response, rather issue, was because I recognize what a needed and well designed project this is Ben from the outset.

I don’t want to fork the repository and make it into a reincarnation of yours by getting rid of piracy checks but ,  prior to ever chatting with you, I did not know your stance on this and how you felt about it. I’m going to try to brainstorm a little bit and I will get back on the ass, with any possible ideas I have, as quickly as possible .

@jlippold  no I do not have a pro piracy stance at all, on the contrary I do not believe in, nor use, pirated software… That is, assuming I know I’m not using it!  I have been a software developer for well over 35 years  and the majority of my work is in the public domain. Unfortunately several of my companies that I own perform work for highly sensitive corporations and/or the government and so most of my repose on get hub are currently private. I am going to be releasing a lot of my source code very soon and it is scattered around the web on other sites also. 

My issue is with the blanket flagging of every single repo in a ‘pirate’ source as being pirated.  Perhaps implementing a checksum validating mechanism might assay some of the concerns the people at r/jailbreak have.  in other words, if they check some of the repository hosting a genuinely valid tweak matches that of the initial or primary source repository, then I believe it would be safe to assume the two pieces of software are identical.    while there are methods to circumvent this, I believe the time, effort, skill and, frankly the benefit to the person attempting to circumvent these measures make such concerns nil.

Thanks again for your rapid response and interest in finding a solution for this. Please let me know whatever I can do to help.

Please note one thing, however. I am also a member of the Linux kernel netfilter and general networking stack programming team, the BIND nameserver senior development team, and a  heavily involved developer over at WikiMedia (which runs Wikipedia, of course,) so sometimes it might take me a little time to respond but I will definitely always respond eventually. Please forgive any delays in advance .

**Comment by PJ09github** [comment]
@jlippold since you mentioned me about [this ](https://github.com/jlippold/tweakCompatible/issues?utf8=%E2%9C%93&q=Pirate+Repo) i just explained you that those repos contain piracy/pirated tweaks. 

We are removing only piracy/pirated tweaks and illegal repos.

**Comment by jlippold** [comment]
Ok if you come up with something @sietec let me know. I don't think I can pull a checksum from cydia, but I'm open to pull requests if you want to take a stab at it.

@PJ09github sorry I tagged you in this. I thought the complaint was about a misreported pirate repo, and since you're the only active mod on here, I assumed it was a mistake on your part. My apologies.

**Comment by PJ09github** [comment]
@jlippold no problem

Inviato da iPad

**Comment by sietec** [comment]
@jlippold Thanks for the information.  To be completely honest, my area of expertise is with (Obj)C(++) and other similar “low level” languages.  I am considering working on a native iOS/macOS/tvOS app whoch could ... Sorry I just realized I don’t really want to discuss the details publicly... so, if you want to know more about this, let me know and I’ll grant you access to my a corporate repo of mine (private) or my sharepoint site where we can discuss it.

For Your Information, not that I think you are feeling this way, but I would never take someone else’s work and create something newer/etc. without their express permission and their agreement on the project.   essentially what I am saying is you have created an awesome and really powerful tool which thousands of people have come to rip lie upon, it is your creation, not mine, I will be more than happy to help in any capacity I can but I do not want to step on any toes and I would never cross a boundary of stealing someone else’s work or masquerading my work as someone else’s.

Thanks again

**Comment by sietec** [comment]
@jlippold I am actively working on a solution to this... I do know of a method to obtain a checksum from Cydia (not really, because it's more in the backend... the debian packing commands apt-get and aptitude, etc.) but it is very straightforward and is not a 'hack' method in any way.  I believe in clean code and code done right (e.g. no shortcuts, no hacking public projects in order to get some functionality that is not typically obtainable, etc.)

I apologize for my prolonged absence.  I was in hospital for 8 days with a severe infection and had to have surgery on my leg.  Doing good now, but obviously, wasn't able to do much with all the drugs they were giving me etc.

If you'd prefer to continue this topic in private, to keep it from distracting from the main goal of your project and/or to keep confusion to a minimum, please just let me know your preferred method of doing so.  One way is for me to add you to the repo I will be creating for my "hopefully" better solution, and keep it a private repo until things look good.

Just let me know what works for you, if your interested in this, and how I can help you to expedite more accurate piracy checks.

Thanks!

**Comment by jlippold** [comment]
I'm not 100% sure what you're building but just send a pull request

**Comment by sietec** [comment]
@jlippold Sorry for the vague description... I've been out of town for a week and will be back tomorrow.  At that time, I'll start work on what I'm describing and give you a better idea of what I am talking about.

When completed and, if you like the modifications, I will submit a PR and we can go from there.

You've done a beautiful job with this project, I know that when working with dozens, hundreds or even thousands of requests (e.g. the piracy ban requests from various repos), things can become very time consuming and frustrating by trying to make everyone happy!  I hope you see my comments here, as well as upcoming ideas, as a _positive_ and _constructive_ observation/critique...not as a gripe and moan fest!

I'll be in touch soon.
